services:

  mysql:
    image: mysql:5.7
    container_name: mysqldocker
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: brimos
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
