basePath: /
definitions:
  dto.CreateUserInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  handlres.Error:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: guiyonesnogara@gmail.com
    name: Guilherme Yones Nogara
    url: https://github.com/guiyones
  description: Product API with authentication
  license:
    name: Brimos License
    url: https://github.com/guiyones/brimos
  termsOfService: http://swagger.io/terms/
  title: Brimos
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Create user
      parameters:
      - description: user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlres.Error'
      summary: Create user
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authentication
    type: apiKey
swagger: "2.0"
